User_Profiles/portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_profile.urls')),
]

User_Profiles/portfolio/user_profile/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'user_profile'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.user_profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/change-password', views.change_password, name='change-password')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

User_Profiles/portfolio/user_profile/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfileInfo(models.Model):
    """
    This model class has one one to relation with Django Admin's
    Model User. This class is basically used extend User Model
    fields
    """
    # one to one relation with user
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Extra fields
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

User_Profiles/portfolio/user_profile/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm

from .models import UserProfileInfo


class UserForm(forms.ModelForm):
    """
    This form class is using Django Admin User Model's
    fields, we also add new fields in it 'password'
    """
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    """
    form class using UserProfileInfo model created in models.py
    this has one-to-one relation with User Model
    """
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')


class EditProfileForm(UserChangeForm):
    """
    This form is inherit from Django Auth Forms
    to change user password
    """
    class Meta:
        model = User
        fields = ('email', 'first_name',
                  'last_name', 'password')

User_Profiles/portfolio/user_profile/views.py
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.shortcuts import render

from .forms import UserForm, UserProfileInfoForm, EditProfileForm
from django.contrib.auth.forms import PasswordChangeForm


def index(request):
    return render(request, 'user_profile/index.html')


def register(request):
    """
    This view function is used to Register new users to
    website, using UserForm and UserProfileInfoForm from
    forms.py . verify all data and save it in User and UserProfileInfo
    Tables
    :param request:
    :return:
    """
    # to send template to check user authorization
    registered = False

    if request.method == "POST":
        # get all data post in form through request and save it in user_form , profile_form
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        # check if post data is valid
        if user_form.is_valid() and profile_form.is_valid():

            # if valid save data in User and UserProfileInfo tables in Database
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'user_profile/registration.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered
                   })


def user_login(request):
    """
    This view function is used to Login registered users to
    website, using Login form. verify login details from database
    using django.admin builtin function authenticate
    :param request:
    :return:
    """
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        # Authenticate user from Database
        user = authenticate(username=username, password=password)

        # if user is authenticated
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('user_profile:index'))
            else:
                return HttpResponse("Account is Inactive")

        else:
            return HttpResponse("Invalid login details")

    else:
        return render(request, 'user_profile/login.html', {})


@login_required()
def user_logout(request):
    """
    Logout authenticated users from website
    :param request:
    :return:
    """
    logout(request)
    return HttpResponseRedirect(reverse('user_profile:index'))


@login_required()
def user_profile(request):
    """
    Provide user profile page consisting of all
    current users details
    :param request:
    :return:
    """
    current_user = request.user
    return render(request, 'user_profile/profile.html', {'user': current_user})


@login_required()
def edit_profile(request):
    """"
    Edit current user profile, get instance of request user
    goto EditProfileForm inherit from ChangeForm
    """
    if request.method == "POST":
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('user_profile:profile'))

    else:
        form = EditProfileForm(instance=request.user)
        return render(request, 'user_profile/edit_profile.html', {'form': form})


@login_required()
def change_password(request):
    """
    Change Login user password using
    Builtin class PasswordChangeForm from Django.contrib.auth.forms
    :param request:
    :return:
    """
    if request.method == "POST":

        form = PasswordChangeForm(request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return HttpResponseRedirect(reverse('user_profile:profile'))
        else:
            return HttpResponseRedirect(reverse('user_profile:change-password.html'))

    else:
        form = PasswordChangeForm(user=request.user)
        return render(request, 'user_profile/edit_profile.html', {'form': form})

User_Profiles/portfolio/templates/user_profile/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
      integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css"
      integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
        integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'user_profile:index' %}">Home</a> </li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a> </li>

                {% if user.is_authenticated %}
                    <li><a class="navbar-link" href="{% url 'user_profile:logout' %}">Logout</a> </li>
                    <li><a class="navbar-link" href="{% url 'user_profile:profile' %}">Profile</a> </li>
                    <li><a class="navbar-link" href="{% url 'user_profile:edit_profile' %}">Edit Profile</a> </li>
                    <li><a class="navbar-link" href="{% url 'user_profile:change-password' %}">Change Password</a> </li>
                {% else %}
                    <li><a class="navbar-link" href="{% url 'user_profile:user_login' %}">Login</a> </li>
                    <li><a class="navbar-link" href="{% url 'user_profile:register' %}">Register</a> </li>
                {% endif %}
            </ul>
        </div>
    </nav>

<div class="container">
    <div class="jumbotron">
        {% block body_block %}
        {% endblock %}
    </div>

</div>
</body>
</html>

User_Profiles/portfolio/templates/user_profile/change-password.html
{% extends 'user_profile/base.html' %}
{% load staticfiles %}

{% block body_block %}

<div class="container">
      <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.as_p }}
      </form>
</div>
{% endblock %}

User_Profiles/portfolio/templates/user_profile/edit_profile.html
{% extends 'user_profile/base.html' %}
{% load staticfiles %}

{% block body_block %}

<div class="container">
      <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.as_p }}
      </form>
</div>
{% endblock %}

User_Profiles/portfolio/templates/user_profile/index.html
{% extends "user_profile/base.html" %}
{% block body_block %}

    <h1>Welcome to User Profile Django App</h1>

{% endblock %}

User_Profiles/portfolio/templates/user_profile/login.html
{% extends 'user_profile/base.html' %}
{% block body_block %}

<div class="container">
    <h1>Please login here..</h1>
    <form action="{% url 'user_profile:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username: </label>
        <input type="text" name="username">

        <label for="password">Password: </label>
        <input type="password" name="password">

        <input type="submit" class="btn btn-default" value="Login">
    </form>
</div>
{% endblock %}

User_Profiles/portfolio/templates/user_profile/profile.html
{% extends 'user_profile/base.html' %}
{% block body_block %}

<div class="container">
    <img src="{{ user.userprofileinfo.profile_pic.url }}" width="500" height="500">
    <h1>Welcome {{ user.username }}</h1>
    <p>Name: {{ user.first_name }} {{user.last_name}}</p>
    <p>Email: {{ user.email }}</p>
    <p>Portfolio Site: {{ user.userprofileinfo.portfolio_site }}</p>
</div>
{% endblock %}

User_Profiles/portfolio/templates/user_profile/registration.html
{% extends 'user_profile/base.html' %}
{% load staticfiles %}

{% block body_block %}

<div class="container">
    {% if registered %}
      <h1>Thank you for registering</h1>
    {% else %}
      <h1>Register Here!</h1>
      <h3>Fill out this form to register</h3>
      <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input class="btn btn-primary" type="submit" value="Register">
      </form>
    {% endif %}
</div>
{% endblock %}